name: 02-2 - Delivery - Trivy Scan

on:
  workflow_call

env:
  REGISTRY: ghcr.io
  USERNAME: ${{github.actor}}
  IMAGE_NAME: ${{github.repository}} #orga/repo

jobs:
  Trivy_Scan_Back:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{env.USERNAME}}
          password: ${{secrets.MONOREPO_PAT}}

      - name: Downcase Image Name
        run: echo "IMAGE_NAME_LOWER=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Trivy BACK vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{env.REGISTRY}}/${{env.IMAGE_NAME_LOWER}}-back:canary
          format: 'table'
          exit-code: '1'
          output: 'back-trivy-results.txt'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Upload Trivy results BACK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: back-trivy-results
          path: back-trivy-results.txt
          retention-days: 1

  Trivy_Scan_Front:
    runs-on: ubuntu-latest

    steps:
      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{env.USERNAME}}
          password: ${{secrets.MONOREPO_PAT}}
          
      - name: Downcase Image Name
        run: echo "IMAGE_NAME_LOWER=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Trivy FRONT vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        if: always()
        with:
          image-ref: ${{env.REGISTRY}}/${{env.IMAGE_NAME_LOWER}}-front:canary
          format: 'table'
          exit-code: '1'
          output: 'front-trivy-results.txt'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Upload Trivy results FRONT
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: front-trivy-results
          path: front-trivy-results.txt
          retention-days: 1